name: CI

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: 'Who to greet'
        required: false
        default: 'World'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: jpadams/js-shim-dagger-go-action@main
        with:
          who-to-greet: ${{ github.event.inputs.who-to-greet }}
