name: CI

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: 'Who to greet'
        required: false
        default: 'World'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set who to greet
        id: who-to-greet
        run: |
          USER_INPUT=${{ github.event.inputs.who-to-greet }}
          echo "::set-output name=value::${USER_INPUT:-"Dagger Go SDK"}"

      - uses: jpadams/js-shim-dagger-go-action@main
        with:
          who-to-greet: ${{ steps.who-to-greet.outputs.value }}
